### ISSUE TITLE
可以加入 Memcached 的支持？

### ISSUE THREAD

**Issue by willove** [jasonweicn/MicroFramework#4]
我系统环境里没有安装Memcache扩展而是安装了Memcached，然后尝试在 Cache_Memcache 的基础上把 Memcached 的缓存类给写出来，暂时先这么应付，希望后续可以更新。

然后 Mini 下的 Cache.php 判断 $adapter 用到 function_exists 检查是有些不妥吧，应该用 class_exists 。

**Comment by jasonweicn** [comment]
感谢您的建议和bug反馈，1.0.7中已经加入了对memcached扩展的支持。
