### ISSUE TITLE
当在Public目录中执行 php -S localhost:3000 时

### ISSUE THREAD

**Issue by codetyphon** [jasonweicn/MicroFramework#7]
出现如下错误

NOTICE: Undefined index: argc in miniframework-app-basic/vendor/jasonweicn/miniframework/Base/Router.php on line 85 NOTICE: Undefined index: argc in miniframework-app-basic/vendor/jasonweicn/miniframework/Base/Request.php on line 207

**Comment by jasonweicn** [comment]
多谢反馈，已在Master主分支中进行了修复。
