### ISSUE TITLE
demo中api/version测试有问题。已解决

### ISSUE THREAD

**Issue by PndOS** [jasonweicn/MicroFramework#8]
查询trace错误提示 app.php行217。
原文少了Base，改成如下OK
原文 if ('Mini\\Rest' !== get_parent_class($apiName)) {
 改成if ('Mini\\Base_\\Rest' !== get_parent_class($apiName)) {
，另外，还有个坑，如果上个问题没有解决的话，再按F5重试一下的话，错误提示竟然变化了，Client CSRF-Token invalid，在app.php 行177，而不是行217。很是抓狂的：（。。。。。后来想到cookie的保存原因，然后，打开调试工具，清空cookie中才正常。

**Comment by PndOS** [comment]
http://localhost:8091/api/info_v2
提示PHP Fatal error:  Uncaught Mini\Base\Exception: Controller name invalid. in D:\php\miniframework-2.1.0\MiniFramework\Base\Router.php:122。
原因在于这里，未支持下划线,要改
protected function checkRoute($value)
    {
       将 return preg_match("/^[a-zA-Z][a-zA-Z0-9]*$/", $value);
改成    return preg_match("/^[a-zA-Z][a-zA-Z0-9_]*$/", $value);
    }

 $info = 'Hello World!(V' .$headers["Ver"] . ')'; //这个也有错误，$headers没有Ver变量

**Comment by jasonweicn** [comment]
非常感谢您的反馈，确实存在Bug，修复后的文件已经提交到Master主干分支了。

**Comment by jasonweicn** [comment]
> http://localhost:8091/api/info_v2
> 提示PHP Fatal error: Uncaught Mini\Base\Exception: Controller name invalid. in D:\php\miniframework-2.1.0\MiniFramework\Base\Router.php:122。
> 原因在于这里，未支持下划线,要改
> protected function checkRoute($value)
> {
> 将 return preg_match("/^[a-zA-Z][a-zA-Z0-9]_$/", $value); 改成 return preg_match("/^[a-zA-Z][a-zA-Z0-9_]_$/", $value);
> }
> 
> $info = 'Hello World!(V' .$headers["Ver"] . ')'; //这个也有错误，$headers没有Ver变量


关于这个问题，并非有Bug，这是一个版本号的demo文件，不是直接在URL中访问info_v2，而是通过在请求Header中加入Ver（版本号）参数，以达到在请求地址不变的情况下（请求地址依旧是/api/info），访问不同版本接口的目的。

例如：请求地址为/api/info时，请求header中Ver=2，那么miniframework会根据您传入的版本号，自动调用Info_v2.php。header中不带Ver=2时，miniframework会调用Info.php，感兴趣的话您可以尝试一下。

下边是我在那个demo文件中的注释：

//这是一个演示API版本控制的demo
//说明：向Header中加入Ver（版本号）参数，Ver的值必须是一个整数；API文件名和类名加后缀_VX（X为版本号）

**Comment by PndOS** [comment]
谢谢。受教了

**Comment by jasonweicn** [comment]
> 谢谢。受教了

客气了
