### ISSUE TITLE
v2.4几个小Bug反馈一下

### ISSUE THREAD

**Issue by freshwind2004** [jasonweicn/MicroFramework#9]
1. Cache下面的抽象类好几个方法都没写全（例如connect、getExtendedStats），导致无法使用。Cache的Memcached和Redis类貌似都是半成品。
2. createCsrfToken逻辑错误，应该是ctrl+v的时候错位了。（错误：检验了session和cookie相同后，又重建了新的token，导致session和cookie的token总是不同。位于Base\App.php。）
3. pathinfo传值问题。/?page=1可以但是/page/1/就不行。尝试了Apache和Nginx，都没成功。也可能不是Bug，是我配置不对。

很喜欢miniframework这种微型框架，正在通过它学php，希望作者继续完善。

**Comment by jasonweicn** [comment]
首先，非常感谢 @freshwind2004 的关注！下面我逐一解答您的问题。

**问题1：**
Cache下面的抽象类好几个方法都没写全（例如connect、getExtendedStats），导致无法使用。Cache的Memcached和Redis类貌似都是半成品。
**解答：**
正如您最后一句所述，MiniFramework 的确是一个非常微型的框架，就像我在框架简介中所写的——“满足开发者最基础的分层开发、数据库和缓存访问等少量功能基础上，做到尽可能精简”。所以例如 Cache 模块，定位就是解决缓存的读写。所以，会给您没有写全或是半成品的感觉，因为除了最基本的缓存读写（set/get）外，其他的功能并非我所关注的重点。因此，其他的功能并未加入到其中。不过，考虑到可能会有开发者需要 set/get 以外的功能，我分别在Memcache、Memcached和Redis中，预留了 getMemcacheObj、getMemcachedObj 和 getRedisObj 三个方法，用于获取他们的实例，以便开发者通过实例来使用框架中没有封装的方法。（这三个获取实例的方法我在文档中也有提及，可以关注一下[http://www.miniframework.com/docv2/guide/shi-yong-huan-cun.html](http://www.miniframework.com/docv2/guide/shi-yong-huan-cun.html)）
另外，您提到的没有 connect 方法导致无法使用的问题，我在开发 Cache 模块时，采用的是惰性连接的方式，只在需要读写时，才去主动连接，并且不需要开发者自己连接，在类的内部已经实现了自动连接，具体代码请到 Memcache、Memcached 和 Redis 三个类中查找 _connect 方法。关于 Cache 的使用方法，还是请到上边的那个文档地址中了解一下。

**问题2：**
createCsrfToken逻辑错误，应该是ctrl+v的时候错位了。（错误：检验了session和cookie相同后，又重建了新的token，导致session和cookie的token总是不同。位于Base\App.php。）
**解答：**
关于 CSRF 机制，每次校验后，均会生成一个新 TOKEN 是正常的流程。正确的使用方法是：需要开发者在所有页面中，主动调用 Mini\Helpers\Safe::getCsrfToken() 方法来获取最新的 TOKEN，并通过 cookie、post、get 或 header 方式向下一个页面传递，框架会自动从上述这些渠道中检测是否传入了 TOKEN 并进行校验，如果未找到或校验无效，会报异常，从而保护您的页面不会被第三方轻易进行跨站攻击。

**问题3：**
pathinfo传值问题。/?page=1可以但是/page/1/就不行。尝试了Apache和Nginx，都没成功。也可能不是Bug，是我配置不对。
**解答：**
这个问题我猜是您还不熟悉这个框架的伪静态规则，相关文档在[http://www.miniframework.com/docv2/guide/wei-jing-tai.html](http://www.miniframework.com/docv2/guide/wei-jing-tai.html)
框架默认的规则为http://localhost/Controller/Action/param1/value1/param2/value2
控制器（Controller）和动作（Action）是不能省略的。

最后，再次感谢 @freshwind2004 朋友的关注，欢迎多多交流，我也会尽力来完善MiniFramework。

**Comment by freshwind2004** [comment]
谢谢作者抽空回复 ！

关于第一个问题，按照文档：
```
$cache = \Mini\Cache\Cache::factory ('Memcache',
    array (
        'host'      => 'localhost', //主机
        'port'      => 11211        //端口
    )
);
```
实例化后就报错了，说找不到Memcache Class，修改源代码中的：
`$this->_cache_server = new \Memcache();`
为
`$this->_cache_server = new Memcache();`
Class不报错，但是报错找不到getExtendedStats()
`$memStats = $this->_cache_server->getExtendedStats();`
查找了Memcache和Abstract都没有看到getExtendedStats()这个方法，不知道错在哪里。

关于第二个问题，我指的这段代码：
 ```
 // Check CSRF-Token
        if (CSRF_TOKEN_ON === true) {
            if ($isCli === false) {
                $serverCsrfToken = $this->_request->loadCsrfToken('session');
                if (! $serverCsrfToken) {
                    $this->_request->createCsrfToken(CSRF_TYPE);
                } else {
                    **if ($this->_request->checkCsrfToken() === true) {
                        $this->_request->createCsrfToken(CSRF_TYPE);
                    }** else {
                        throw new Exception('Client CSRF-Token invalid.');
                    }
                }
            }
        }
```
如果保持黑体部分原样的话，loadCsrfToken('session') 就总是不等于loadCsrfToken('cookie')。
在App中checkCsrfToken()总是返回false。
设计初衷是这样吗？

关于第三个问题，按照MiniAdmin例子的写法：

`$page = isset($_GET['page']) && preg_match('/^\d+$/', $_GET['page']) ? intval($_GET['page']) : 1;`

url为 localhost.com/portfolio/index/page/1(/)
始终捕获不到$page。
但是 localhost.com/portfolio(/)?page=1 或者 localhost.com/portfolio/index(/)?page=1 都可以捕获$page
开发环境是win10 + xampp。

**Comment by jasonweicn** [comment]
根据您的描述，的确发现 Cache 模块存在一些Bug，主要集中在 Memcached 和 Redis 两个 Class 上，已经进行了修复，请关注一下2.4.1版本。
另外，您说的 Memcache 的问题，我这边一直无法复现出来，请您确认一下 PHP 安装的是Memcache扩展？还是Memcached扩展？如果是Memcached扩展，请按下面的代码实例化：

`$cache = \Mini\Cache\Cache::factory ('Memcached',
    array (
        'host'      => 'localhost',
        'port'      => 11211
    )
);`

再次感谢您的反馈！

**Comment by jasonweicn** [comment]
另外，关于通过$_GET取不到值的问题，当采用伪静态运行时，需要通过框架内置的方法来获取，例如：

`$params = $this->params->getParams(); //获取全部参数`
`dump($params);`

或者，也可以这样：

`$page = $this->params->getParam('page'); //获取指定的参数`
`dump($page);`

这样设计的初衷是尽量不去污染$_GET

**Comment by freshwind2004** [comment]
非常感谢指导！

memcached可以正常工作了。pathinfo也正常使用中。
`$this->params->getParam();` 
这个设计很赞，可是我看源码一知半解，比较依赖文档，不然应该能够自己找出来，哈哈

文档关于缓存的例子有一个笔误，memcached少了一个d。

**Comment by jasonweicn** [comment]
不客气，欢迎多多交流，个人精力有限，文档的详细程度确实不理想，见谅！

PS：memcache扩展也是被支持的，所以在实例化时，既可以传入Memcache，也可以传入Memcached，具体用哪个，根据PHP安装的哪个扩展来决定。
